### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PauloLosse** [PauloLosse/first_audio_player#1]
- [x] Create this repository and upload the first version of the code
- [x] Create a page for it on Netlify
- [x] Solve the "mouse over" and "mouse out" button icon change problem
- [x] Add a app icon
- [x] Use a better background
- [x] Create a functional progress bar
